### ISSUE TITLE
crestmatic only documents representations it can find without authentication

### ISSUE THREAD

**Issue by regner** [jimpurbrick/crestmatic#2]
An example of this is you have the AllianceCollection-v1 but don't have the Alliance-v1 resource which is linked to from the AllianceCollection-v1.

Let me know if this is something screwy on the CREST end and I will dig into it.

**Comment by jimpurbrick** [comment]
This is because crestschemaspider.js isn't currently sending auth headers from travis. It can make an OPTIONS request to the alliances collection to get the AllianceCollection-v1 representation metadata, but gets a 401 Unauthorized when making a GET request to https://crest-tq.eveonline.com/alliances/. It can't get a URI to an alliance resource, so can't make an OPTIONS request to a URI which will describe the Alliance-v1 representation. I'm looking at ways to allow crestschemaspider.js to make authenticated CREST calls securely now.

**Comment by regner** [comment]
Is there a reason we didn't allow OPTIONS calls in public CREST?

**Comment by jimpurbrick** [comment]
OPTIONS requests always succeed without authentication (curl -X OPTIONS https://crest-tq.eveonline.com/alliances/500003/), but in order to get the OPTIONS response the spider has to find the URI of an alliance, which it can't as the GET request to the alliance collection fails without authentication (curl https://crest-tq.eveonline.com/alliances/500003/).

**Comment by jimpurbrick** [comment]
Also, this is fixed as of https://github.com/jimpurbrick/crestmatic/commit/1e8d6cf2633c71138e229b4eca5bda9e761fb061
